### ISSUE TITLE
Scene zoomed with a double tap even if StopResponding is called

### ISSUE THREAD

**Issue by fede9876** [Cheesebaron/SkiaScene#10]
A scene can be zoomed with a double tap even if StopResponding method of class SceneGestureResponder is called.

**Comment by OndrejKunc** [comment]
Hi, thanks for reporting the issue.

I fixed it by https://github.com/OndrejKunc/SkiaScene/commit/8b571c58c64ca964a677ed63cee5fdb980427cbb

And I just also published updated packages with the fix.
