### ISSUE TITLE
Touch gesture not work in release build in UWP

### ISSUE THREAD

**Issue by bdndreams** [Cheesebaron/SkiaScene#12]
I have used Skiascene and touchmanipulation in my UWP application. It is works fine in Debug build, but when I was generated release build for UWP and installed on my machine, touch gesture is not working.

Can you please give me solution to work this in release build also.

**Note:** This issue in on UWP only, on Android release build it is works fine

**Comment by OndrejKunc** [comment]
Hi, thanks for opening the issue.

It looks like the same problem that was discussed in #6 .

I just updated the documentation and the UWP example via #13 .

You just need to provide explicit Assembly parameter to your Xamarin.Forms.Init method in App.Xaml.cs inside UWP project:

`Xamarin.Forms.Forms.Init(e, new[] { typeof(TouchTracking.Forms.UWP.TouchEffect).Assembly });`

Please tell me if it solved your problem.

**Comment by JogyBlack** [comment]
Hi,
Just to let you know,I encountered the same problem in my app, and changing the Xamarin.Forms.Init did solve it. 
Thanks,
Jogy
