### ISSUE TITLE
Gestures very twitchy on some newer Android devices

### ISSUE THREAD

**Issue by Cheesebaron** [Cheesebaron/SkiaScene#19]
On Samsung Galaxy S20+ and Sony Xperia 5 when trying to tap the Skia view, a pan gesture seems to also be detected and moving the view slightly.

It would be nice if the gesture detection on Android could account for Touch Slop before attempting to pan. The slop for the device can be retrieved with `var slop = ViewConfiguration.Get(Context).ScaledTouchSlop;`.

Then there needs to be added some logic to detect whether the pan gesture has surpassed the touch slop and only then start it and start firing to the MoveByVector method.

**Comment by Cheesebaron** [comment]
Seems like taps on Android also invoke: SceneGestureRenderingResponder.TouchGestureRecognizerOnPan even if it is only a tap and it in turns calls MoveByVector, this isn't really ideal.

**Comment by OndrejKunc** [comment]
Hi @Cheesebaron ,
Thanks for the valuable feedback and for the PRs! 
I wasn't able to reproduce it on my old Google Pixel device but I believe this can be a problem on other devices. I will check the pull requests.
