### ISSUE TITLE
TouchRecognizer.TouchesBegan on iOS throws System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by paulelong** [Cheesebaron/SkiaScene#2]
I only see this on iOS.  Windows and Android seems to work fine.  It repro's on both physical hardware and the emulator.  Just by clicking or probing and sliding in the touch area.

Application.Main (System.String[] args)
System.ArgumentException: An item with the same key has already been added. Key: 4506795616
1
Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior)
2
Dictionary`2[TKey,TValue].Add (TKey key, TValue value)
3
TouchRecognizer.TouchesBegan (Foundation.NSSet touches, UIKit.UIEvent evt)
4
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
5
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
6
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
7
Application.Main (System.String[] args)

**Comment by OndrejKunc** [comment]
This looks like the same issue described here #1 
The problem occurs when your layout is nested inside ScrollViewer or other component which can cause touch conflicts and we are not able to detect release finger event.
If this is your case I would recommend to get rid of the ScrollViewer or set flag CancelsTouchesInView to false on your parent component which may allow child controls to receive all touch events. See https://stackoverflow.com/questions/22127451/touches-ended-not-being-called

**Comment by paulelong** [comment]
This makes sense, as I recently add the MasterDetailPage mechanism.  I don't understand why it's iOS specific though.

I attempted the CancelsTouchesInView=false solution but overriding ViewDidLoad in PageRenderer.  I wasn't sure how to target a specific parent, so I iterated though all subviews and printed the value of CancelsTouchesInView and all were false already.  I also saw another solution, which I tried, but none of these made a difference.  I've put the code below.

Am I doing this properly?

Does this mean that DetailsMasterPage isn't compatible with TouchEffects?


    class MainPageRenderer : PageRenderer
    {
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            pViews(View, 0);


            View.MultipleTouchEnabled = false;

            var cp = Element as MainPage;
            if (cp != null)
            {
                foreach (var g in View.GestureRecognizers)
                {
                    g.CancelsTouchesInView = false;
                }
            }

            pViews(View, 0);
        }

        public void pViews(UIView v, int indent)
        {
            foreach(var x in v.Subviews)
            {
                if(x.GestureRecognizers != null)
                {
                    for (int n = 0; n < indent; n++)
                    {
                        Debug.Write(" ");
                    }
                    Debug.WriteLine("Name is " + x.Description);
                    foreach (var g in View.GestureRecognizers)
                    {
                        Debug.WriteLine(" **val is " + g.CancelsTouchesInView.ToString());
                        g.CancelsTouchesInView = false;
                    }
                }
                pViews(x, indent + 1);
            }
        }

I also saw another solution that

**Comment by paulelong** [comment]
My conclusion at this point is that the system menu for iOS doesn't support edge swipe, which is the difference between other OS's.  I can disable the swipe completely with this code in the Master Detail init constructor.  Now maybe I can find a way to add edge swipe back.

            if(Device.RuntimePlatform == Device.iOS)
            {
                IsGestureEnabled = false;
            }

**Comment by OndrejKunc** [comment]
Should be fixed via #11

**Comment by IainS1986** [comment]
Is there a release of SkiaScene (or more specifically SkiaScene.TouchManipulation) with this in?

I'm on SkiaScene.TouchManipulation 2.2.0 which appears to just have SkiaScene 1.0.0 internally and TouchTracking 1.1.0

**Comment by OndrejKunc** [comment]
Hi @IainS1986  
I just published SkiaScene.TouchManipulation 2.2.1 which depends on TouchTracking 1.2.0 and the fix should be there.

**Comment by IainS1986** [comment]
@OndrejKunc  Awesome cheers!

Just FYI, I always get a warning with using ITouchGestureRecognizer in the TouchTracking with regards to SkiaSharp version reference.

It always says the following (with version 2.80 changing as I upgrade SkiaSharp),

`CS1701: Assuming assembly reference 'SkiaSharp, Version=1.59.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' used by 'SkiaScene.TouchManipulation' matches identity 'SkiaSharp, Version=2.80.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' of 'SkiaSharp', you may need to supply runtime policy`

Assuming something in SkiaScene or TouchTracking is still referencing an older version of SkiaSharp?
