### ISSUE TITLE
Android throws System.ObjectDisposedException: when returning to a page with Skia. UWP and iOS work fine

### ISSUE THREAD

**Issue by WillAutioItrax** [Cheesebaron/SkiaScene#4]
I had initially posted this issue on the SkiaSharp page here:
https://github.com/mono/SkiaSharp/issues/735
Matt looked into it and determined that the issue originates in SkiaScene.

And here is what I had posted by way of describing the bug and a repro that shows the bug:

Description
Returning to a Page with a Skia Canvas in Android causes an exception
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.Platform+DefaultRenderer'.
Both UWP and iOS work fine. I have a Master/Detail app with one page using SkiaSharp for drawing. Sometimes I need to go to a different page to get some info and then return to the drawing to continue with the Sketch. That is when, in Android, I get the Exception.
It starts with:
12-17 08:37:04.941 I/MonoDroid(12405): System.ObjectDisposedException: Cannot access a disposed object.
12-17 08:37:04.941 I/MonoDroid(12405): Object name: 'Xamarin.Forms.Platform.Android.Platform+DefaultRenderer'.

Code
Below is a link to a repro.

Expected Behavior
To move successfully between detail pages.

Actual Behavior
Upon returning to the page with Skia I get System.ObjectDisposedException

Basic Information
Version with issue: SkiaSharp v 1.68.0
Last known good version: new code, never run before
IDE: VS 2017 v 15.9.4
Platform Target Frameworks:
Android: 8.1 (Oreo)

Alcatel 9024O Android v 7.1.1

Samsung SM-G960W Android v 8.0

Screenshots
Reproduction Link
https://bitbucket.org/WillAutio/skiafail

Thanks for looking at this.

**Comment by OndrejKunc** [comment]
Thanks for reporting this issue.
Fixed by #5 
Just published new nuget package TouchTracking 1.0.1
I downloaded your repo, updated TouchTracking to 1.0.1 in all projects, cleaned solution and it looks like it fixed this issue.

**Comment by WillAutioItrax** [comment]
@OndrejKunc Works like a charm. Thanks!

**Comment by OndrejKunc** [comment]
@WillAutioItrax No problem :)
