### ISSUE TITLE
[TouchTracking.Forms] Does not work on iOS when built in release mode

### ISSUE THREAD

**Issue by jasekiw** [Cheesebaron/SkiaScene#8]
I downloaded your library and it worked really well in debug mode. As soon as I switched it to release mode, all instances of this library don't fire the touch event. I'm using it exactly like it is used in the sample project.

**Comment by OndrejKunc** [comment]
And does it work in the sample app?
Maybe the root cause is the absence of this line in the AppDelegate FinishedLaunching:
`var touchEffectType = typeof(TouchTracking.Forms.iOS.TouchEffect);`
Have you included this line in your project as well?

**Comment by jasekiw** [comment]
@OndrejKunc Yes I have included that line and it worked in debug mode but not in release mode. I have since switched to the [XFormsTouch](https://www.nuget.org/packages/XFormsTouch/) and it worked in release mode no problem. I basically swapped all the usages 1 for 1. That's what makes me think it's an issue in this package.

**Comment by OndrejKunc** [comment]
It looks like this issue https://github.com/xamarin/Xamarin.Forms/issues/3910

**Comment by OndrejKunc** [comment]
To make it work right now you need to use different workaround. Instead of the line posted above use this in your AppDelegate FinishedLaunching:
`var _ = new TouchTracking.Forms.iOS.TouchEffect();`
